title: Visarut's Page
email: visarut.hu@gmail.com
description: >-
  Update: June 6, 2025.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minette3762.github.io/" 
linkedin_username: visarut-hu
github_username:  minette3762

# For footer
first_name: Visarut
last_name: Hauyshelake

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - publication.markdown
  - teaching.markdown
  - about.markdown
  